---
- name: Install some graphical utilities
  apt: name={{ item }} state=present update_cache=yes
  become: true
  with_items:
    - apvlv
    - audacity
    - calibre
    - evince
    - gparted
    - iceweasel
    - meld
    - mpv
    - wireshark
    - xarchiver
    - redshift
    - redshift-gtk

