#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# load fonts that are installed in /usr/share/fonts/local (aren't added to font path by default - see Arch wiki)
xset +fp /usr/share/fonts/local
xset fp rehash

# set background
xloadimage -onroot -center ~/Downloads/bank.jpg
xsetroot -cursor_name left_ptr # use a nice cursor instead of the default X

# Use my custom keymap if available, otherwise use a standard keymap
if [ -f ~/.Xmodmap ]
then
  xmodmap ~/.Xmodmap
else
  #setxkbmap be # I'm using a Belgian azerty keyboard
  setxkbmap -layout dvorak -variant gb # I'm using a britsh dvorak keyboard
  setxkbmap -option caps:escape # use caps as escape
fi

# start xflux (makes screen red at night)
if type "xflux" > /dev/null; then
  xflux -l 50.83 -g 3.26 &
fi

# gpg agent
envfile="$HOME/.gnupg/gpg-agent.env"
if [[ -e "$envfile" ]] && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
    eval "$(cat "$envfile")"
else
    eval "$(gpg-agent --daemon --enable-ssh-support --write-env-file "$envfile" --log-file $HOME/.gnupg/gpg-agent.log)"
fi
export GPG_AGENT_INFO  # the env file does not contain the export statement
export SSH_AUTH_SOCK   # enable gpg-agent for ssh

exec startxfce4

