#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# load fonts that are installed in /usr/share/fonts/local (aren't added to font path by default - see Arch wiki)
xset +fp /usr/share/fonts/local
xset fp rehash

# set background
xloadimage -onroot -center ~/Downloads/bank.jpg
xsetroot -cursor_name left_ptr # use a nice cursor instead of the default X

# Use my custom keymap if available, otherwise use standard dvorak gb layout
if [ -f ~/.Xmodmap ]
then
  xmodmap ~/.Xmodmap
else
  #setxkbmap be # I'm using a Belgian azerty keyboard
  setxkbmap -layout dvorak -variant gb # I'm using a britsh dvorak keyboard
  setxkbmap -option caps:escape # use caps as escape
fi

if type "xflux" > /dev/null; then
  xflux -l 50.83 -g 3.26 # start xflux if installed
fi

exec startxfce4

