# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh
. /usr/share/zsh/site-contrib/powerline.zsh

# User configuration

. ~/.profile
. ~/.zsh_aliases

wiki () {
    dig +short txt $1.wp.dg.cx
}

# For netbeans and other Java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# Completion
eval "$(grunt --completion=zsh)"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
