# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="agnoster"

## 256 colors in tmux
#if [ "$TMUX" = "" ]; then 
#  TERM=xterm-256color tmux
#fi

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

. ~/.profile
. ~/.zsh_aliases
[ -f ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && . ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh  

# Use vi-style bindings
#set -o vi

export EDITOR=vim

# For netbeans and other Java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# Completion

if type "grunt" > /dev/null; then
  eval "$(grunt --completion=zsh)"
fi


