---
- name: Install CUPS packages (server, client, PDF printing support)
  apt: name={{ item }} state=present
  become: true
  with_items:
    - cups
    - cups-client
    - cups-pdf
- name: Copy over new /etc/cups/client.conf
  copy: src=client.conf dest=/etc/cups/client.conf backup=yes force=yes
  become: true
- name: Add user to lpadmin group
  user: name={{ unix_username }} groups=lpadmin append=yes
  become: true

