---

- name: Set up a Debian system with my tools and dotfiles
  hosts: all
  roles:
    - update_upgrade
    - zsh
    - vim
    - debug
    - keepass
    - insync
    - utils_cli
    - utils_graphical
    - cups
    - xflux
    - python_utils
    - gimp
    - spotify
    - xmonad
    - franz

- name: Set up a Debian system with my tools that require root
  become: true
  vars_files:
    - vars/nvm.yml
    - vars/idea.yml
  hosts: all
  roles:
    - pablocrivella.nvm
    - angstwad.docker_ubuntu
    - rdeknijf.intellij
    - java

