---
- name: Install some command line utilities
  apt: name={{ item }} state=present update_cache=yes
  become: true
  with_items:
    - ansible
    - arp-scan
    - cmatrix
    - curl
    #- firmware-iwlwifi
    - flac
    - git
    - nethogs
    - optipng
    - pandoc
    - rsync
    - tree
    - vagrant
    - youtube-dl

